### ISSUE TITLE
Increase IntegrationTest timeout for arm64

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf-pipelines#107]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
TAF Integration Test

### Is this a regression?

 n/a

### Description and Minimal Reproduction [**REQUIRED**]
Security-enabled integration test on Jenkins arm64 is failed due to time out, so increase the timeout from 30min to 45min.

## 🔥 Exception or Error
<pre><code>

n/a
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
main branch

**Anything else relevant?**

**Comment by jumpingliu** [comment]
The integration test is running fine without timeout, so there is no need to reset the time.
Close the issue.

**Comment by jumpingliu** [comment]
reopen the issue for integration-test timeout exceeded.

**Comment by cherrycl** [comment]
Fixed by #111
