### ISSUE TITLE
Got permission denied when running test on centos

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-taf-pipelines#30]
Test failed and got the following error when running test on centos.

`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.`

Since SELinux got upgraded, running docker in centOS got permission denied. Need to add "--security-opt label:disable" in docker run command.

[LF ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-19912)
[Jenkins console log](https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-taf-pipelines/job/functional-test/84/consoleFull)

**Comment by wendy0211** [comment]
fixed by #32 and #33
