### ISSUE TITLE
Update TAF_COMMOM_IMAGE image names

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-taf-pipelines#46]
The image name is removing the prefix `docker`, it should become `nexus3.edgexfoundry.org:10003/edgex-taf-common:latest` and `nexus3.edgexfoundry.org:10003/edgex-taf-common-arm64:latest`

releated: https://github.com/edgexfoundry/edgex-global-pipelines/pull/315

**Comment by cherrycl** [comment]
Fixed.
